import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TextSpeakerProvider } from "@/provider/TextContext";
import AnimatedWrapper from "@/components/Animated-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PineQuest",
  description: "Generated by Team Debuggers",
  icons: {
    icon: "pinequest.ico",
    shortcut: "pinequest.ico",
    apple: "apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TextSpeakerProvider>
          <AnimatedWrapper>{children}</AnimatedWrapper>
        </TextSpeakerProvider>
      </body>
    </html>
  );
}
