import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TextSpeakerProvider } from "@/provider/TextContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PineQuest",
  description: "Generated by Team Debuggers",
  icons: {
    icon: "pinequest.ico", // path to your favicon file
    shortcut: "pinequest.ico", // optional
    apple: "apple-touch-icon.png", // optional for Apple devices
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TextSpeakerProvider>{children}</TextSpeakerProvider>
      </body>
    </html>
  );
}
