import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TextSpeakerProvider } from "@/provider/TextContext";
import AnimatedWrapper from "@/app/components/Animated-wrapper";
import MainHeader from "./components/MainHeader";
import Sidebar from "./components/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LittleReaders",
  description: "Generated by Team Debuggers",
  icons: {
    icon: "pinequest.ico",
    shortcut: "pinequest.ico",
    apple: "apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TextSpeakerProvider>
          <div className="flex h-screen">
            {/* Sidebar - fixed left side */}
            <aside className="w-64 bg-gray-100 shadow-md p-4 fixed h-full left-0 top-0">
              <Sidebar />
            </aside>

            {/* Main content - shifted right */}
            <main className="flex-1 ml-64 overflow-y-auto">
              <AnimatedWrapper>{children}</AnimatedWrapper>
            </main>
          </div>
        </TextSpeakerProvider>
      </body>
    </html>
  );
}
